// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function ClearHistory():Promise<void>;

export function DownloadBatch(arg1:main.BatchRequest):Promise<Array<backend.Result>>;

export function DownloadProfile(arg1:main.ProfileRequest):Promise<Array<backend.Result>>;

export function DownloadURL(arg1:main.DownloadRequest):Promise<backend.Result>;

export function DownloadURLs(arg1:main.BatchRequest):Promise<Array<backend.Result>>;

export function GetDefaultOutput():Promise<string>;

export function GetHistory():Promise<Array<main.HistoryItem>>;

export function OpenFolder(arg1:string):Promise<void>;

export function ScrapeProfile(arg1:string):Promise<Array<backend.PostPreview>>;

export function SelectOutputFolder():Promise<string>;

export function StopBatch():Promise<void>;
