// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DownloadBatch(arg1) {
  return window['go']['main']['App']['DownloadBatch'](arg1);
}

export function DownloadProfile(arg1) {
  return window['go']['main']['App']['DownloadProfile'](arg1);
}

export function DownloadURL(arg1) {
  return window['go']['main']['App']['DownloadURL'](arg1);
}

export function DownloadURLs(arg1) {
  return window['go']['main']['App']['DownloadURLs'](arg1);
}

export function GetDefaultOutput() {
  return window['go']['main']['App']['GetDefaultOutput']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function ScrapeProfile(arg1) {
  return window['go']['main']['App']['ScrapeProfile'](arg1);
}

export function SelectOutputFolder() {
  return window['go']['main']['App']['SelectOutputFolder']();
}

export function StopBatch() {
  return window['go']['main']['App']['StopBatch']();
}
